name: Flatpak

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-3.38
      options: --privileged

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Checkout submodules
        uses: textbook/git-checkout-submodule-action@master

      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Download binaries
        run: |
          cd flatpak
          node download.js
          tar -xvf dot.tar.bz2

      - uses: bilelmoussaoui/flatpak-github-actions@v2
        with:
          bundle: 'dot-nightly.flatpak'
          manifest-path: './flatpak/co.dothq.browser.nightly.yml'

      - uses: actions/upload-artifact@v2
        with:
          name: flatpak
          path: dot-nightly.flatpak
